#!/usr/bin/env python3
"""
Visualize extracted frames with their corresponding 2D keypoint annotations.

Given a video name, this script loads the extracted frames, the frame_mapping.json
generated by extractVideoFrames.py, and the keypoints2d pickle, then overlays
annotations on top of each frame to help verify alignment.
"""

import argparse
import json
from pathlib import Path
import pickle

import cv2
import numpy as np

# COCO-style skeleton definition with limb colors
LIMBS = [
    {"joints": (0, 1), "color": (0, 215, 255)},   # neck
    {"joints": (1, 2), "color": (0, 255, 0)},     # r-shoulder
    {"joints": (2, 3), "color": (0, 255, 0)},     # r-elbow
    {"joints": (3, 4), "color": (0, 255, 0)},     # r-wrist
    {"joints": (1, 5), "color": (255, 0, 0)},     # l-shoulder
    {"joints": (5, 6), "color": (255, 0, 0)},     # l-elbow
    {"joints": (6, 7), "color": (255, 0, 0)},     # l-wrist
    {"joints": (1, 8), "color": (255, 255, 0)},   # torso
    {"joints": (8, 9), "color": (255, 255, 0)},   # hip
    {"joints": (9, 10), "color": (255, 255, 0)},  # r-knee
    {"joints": (8, 12), "color": (255, 128, 0)},  # l-hip
    {"joints": (12, 13), "color": (255, 128, 0)}, # l-knee
    {"joints": (13, 14), "color": (255, 128, 0)}, # l-ankle
    {"joints": (0, 15), "color": (255, 0, 255)},  # head-left
    {"joints": (0, 16), "color": (255, 0, 255)},  # head-right
    {"joints": (15, 17), "color": (0, 165, 255)}, # left eye/ear
    {"joints": (16, 18), "color": (0, 165, 255)}  # right eye/ear
]


def loadKeypoints2d(keypointsDir, videoName):
    """Load keypoints2d pickle for given video."""
    kpPath = Path(keypointsDir) / f"{videoName}.pkl"
    if not kpPath.exists():
        raise FileNotFoundError(f"Keypoints2d file not found: {kpPath}")
    with open(kpPath, "rb") as f:
        data = pickle.load(f)
    return data


def loadFrameMapping(framesDir, videoName):
    """Load frame mapping json created during frame extraction."""
    mappingPath = Path(framesDir) / videoName / "frame_mapping.json"
    if not mappingPath.exists():
        raise FileNotFoundError(f"frame_mapping.json not found: {mappingPath}")
    with open(mappingPath, "r") as f:
        data = json.load(f)
    return data.get("frame_mapping", {})


def drawKeypointsOnFrame(frame, keypoints, minConfidence=0.3):
    """Draw keypoints and colored limbs on a frame."""
    for idx, kp in enumerate(keypoints):
        x, y, conf = kp
        if conf >= minConfidence:
            cv2.circle(frame, (int(x), int(y)), 4, (0, 255, 0), -1)
    
    for limb in LIMBS:
        a, b = limb["joints"]
        if a < len(keypoints) and b < len(keypoints):
            x1, y1, c1 = keypoints[a]
            x2, y2, c2 = keypoints[b]
            if c1 >= minConfidence and c2 >= minConfidence:
                cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), limb["color"], 3)
    return frame


def overlayAnnotations(videoName, framesDir, keypointsDir, outputDir=None,
                       minConfidence=0.3, maxPeople=2, limit=20):
    """Overlay annotations for a single video."""
    framesDir = Path(framesDir)
    outputDir = Path(outputDir) if outputDir else None
    if outputDir:
        outputDir.mkdir(parents=True, exist_ok=True)
    
    kpData = loadKeypoints2d(keypointsDir, videoName)
    keypoints2d = kpData.get("keypoints2d")
    if keypoints2d is None:
        raise ValueError("keypoints2d not found in annotation file")
    
    mapping = loadFrameMapping(framesDir, videoName)
    if not mapping:
        raise ValueError(f"No frame mapping entries found for {videoName}")
    
    frameItems = sorted(mapping.items(), key=lambda x: int(x[0]))
    
    processed = 0
    for frameIdxStr, info in frameItems:
        annotationIdx = info.get("annotation_index")
        filename = info.get("filename")
        if annotationIdx is None or filename is None:
            continue
        if annotationIdx >= len(keypoints2d):
            print(f"Annotation index {annotationIdx} out of range (max {len(keypoints2d)-1}), skipping {filename}")
            continue
        
        framePath = framesDir / videoName / filename
        if not framePath.exists():
            print(f"Frame not found, skipping: {framePath}")
            continue
        
        frame = cv2.imread(str(framePath))
        if frame is None:
            print(f"Could not read frame: {framePath}")
            continue
        
        people = keypoints2d[annotationIdx]
        for personIdx, personKps in enumerate(people[:maxPeople]):
            drawKeypointsOnFrame(frame, personKps, minConfidence=minConfidence)
        
        if outputDir:
            outPath = outputDir / f"{videoName}_{filename}"
            cv2.imwrite(str(outPath), frame)
        else:
            cv2.imshow(videoName, frame)
            key = cv2.waitKey(0)
            if key == 27:  # ESC
                cv2.destroyAllWindows()
                return
        
        processed += 1
        if limit and processed >= limit:
            break
    
    if outputDir:
        print(f"Saved {processed} overlay frames to {outputDir}")
    else:
        cv2.destroyAllWindows()


def main():
    parser = argparse.ArgumentParser(
        description="Overlay keypoint annotations on extracted frames to verify alignment"
    )
    parser.add_argument("--videoName", required=True, help="Video name (without extension)")
    parser.add_argument("--framesDir", default="frames", help="Directory with extracted frames")
    parser.add_argument("--keypoints2dDir", default="keypoints2d", help="Directory with keypoints2d pickles")
    parser.add_argument("--outputDir", default=None, help="Optional directory to save overlay images")
    parser.add_argument("--minConfidence", type=float, default=0.3, help="Minimum keypoint confidence to draw")
    parser.add_argument("--maxPeople", type=int, default=2, help="Max number of people to draw per frame")
    parser.add_argument("--limit", type=int, default=20, help="Max number of frames to visualize (0 for all)")
    
    args = parser.parse_args()
    
    overlayAnnotations(
        videoName=args.videoName,
        framesDir=args.framesDir,
        keypointsDir=args.keypoints2dDir,
        outputDir=args.outputDir,
        minConfidence=args.minConfidence,
        maxPeople=args.maxPeople,
        limit=args.limit if args.limit > 0 else None
    )


if __name__ == "__main__":
    main()


